drop table if exists authorities;
drop table if exists users;
drop table if exists group_authorities;
drop table if exists group_members;

create table users(
                      id int not null auto_increment,
                      username       VARCHAR(50) PRIMARY KEY,
                      password       VARCHAR(250) NOT NULL,
                      user_role      VARCHAR(50) NOT NULL,
                      first_name     VARCHAR(100) NOT NULL,
                      last_name      VARCHAR(100) NOT NULL,
                      account_enabled BOOLEAN NOT NULL DEFAULT true,
                      account_expired BOOLEAN NOT NULL DEFAULT false,
                      account_locked BOOLEAN NOT NULL DEFAULT false,
                      credentials_expired BOOLEAN NOT NULL DEFAULT false,
                      use_2fa BOOLEAN NOT NULL DEFAULT false
);

create table authorities (
                             username varchar_ignorecase(50) not null,
                             authority varchar_ignorecase(50) not null,
                             constraint fk_authorities_users foreign key(username) references users(username)
);
create unique index ix_auth_username on authorities (username,authority);
create table groups (
                        id bigint generated by default as identity(start with 0) primary key,
                        group_name varchar_ignorecase(50) not null
);

create table group_authorities (
                                   group_id bigint not null,
                                   authority varchar(50) not null,
                                   constraint fk_group_authorities_group foreign key(group_id) references groups(id)
);

create table group_members (
                               id bigint generated by default as identity(start with 0) primary key,
                               username varchar(50) not null,
                               group_id bigint not null,
                               constraint fk_group_members_group foreign key(group_id) references groups(id)
);